### ISSUE TITLE
Update user's group when updating group member

### ISSUE THREAD

**Issue by oiooj** [lodastack/registry#223]
In func `UpdateGroupMember` at https://github.com/lodastack/registry/blob/master/authorize/group.go#L185 we need update user's group. @ianwoolf

**Comment by oiooj** [comment]
Also func `SetGroupMember`.

**Comment by oiooj** [comment]
Sorry, @ianwoolf update user's group before call func `UpdateGroupMember `, right?

**Comment by ianwoolf** [comment]
yes  
`UpdateMember `[https://github.com/lodastack/registry/blob/master/authorize/perm.go#L190]  is the interface to update group member, which update the user and group.
`RemoveUser ` only be used to remove user.
